# Generated by Django 5.0.2 on 2024-05-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_paid_status_mylist_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
